"""
State Extractor (Phase L2-I/Phase C-6)
=====================================

A background "gatekeeper" LLM that watches the narrative
generated by MiniMax-M3 and extracts structured state
mutations. Runs on the **local** LM Studio instance
(BAZOOKA), serving Gemma-4 12B (or Gemma-3 12B-Instruct).
Uses temperature=0 (greedy) for full determinism.

Architecture:
  ┌──────────────────────┐
  │  Cloud MiniMax-M3     │  (authoritative narrator)
  └──────────┬───────────┘
             │ narrative + choices
             ↓
  ┌──────────────────────┐    ┌──────────────────────┐
  │  Backend Q6 STEP 2   │ →  │  State Extractor     │
  │  (game_socket.py)    │    │  (this module)       │
  └──────────────────────┘    │  LM Studio:1234      │
                              │  Gemma-4 12B         │
                              │  temperature=0        │
                              └──────────┬───────────┘
                                         │ StateMutation
                                         ↓
                              scene_npc_states, character_states

Key design choices (Phase L2-I/Phase C-6):

  1. STRICT EXTRACTION ONLY — never infers, never
     invents. If the narrative doesn't explicitly state a
     fact, returns empty mutations. The few-shot examples
     and the system prompt enforce this discipline.

  2. EVIDENCE BINDING — every state change must cite a
     verbatim excerpt from the narrative. Cross-validation
     can later check that the cited text actually exists.

  3. DELTA-ONLY OUTPUT — the extractor returns the *change*
     (e.g. {"npc_id": "harbin", "new_status": "dead"}), not
     the absolute state. The backend applies the delta to
     the existing row idempotently.

  4. GREEDY DECODING (T=0) — full determinism so two
     extracts of the same narrative produce byte-identical
     JSON. This is critical for replay safety and idempotency.

  5. ASYNC PARALLEL — runs in parallel with the M3 narrative
     call (asyncio.gather). Does not block the user-facing
     response.

  6. PYDANTIC SCHEMA — strict typing at the API boundary
     catches any malformed JSON before it touches the DB.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
from typing import Any

import httpx
from pydantic import BaseModel, Field, ValidationError

logger = logging.getLogger(__name__)


# ============================================
# Pydantic schema (strict typing for DB write)
# ============================================


class NPCStatusChange(BaseModel):
    """A single NPC's status change detected from the narrative."""

    npc_id: str = Field(
        ...,
        description="The canonical NPC id (e.g. 'npc_halia_thornton').",
    )
    new_status: str = Field(
        ...,
        description=(
            "One of: 'alive' | 'dead' | 'fled' | 'unconscious' | "
            "'hostile' | 'neutral' | 'friendly' | 'absent'."
        ),
    )
    evidence: str = Field(
        ...,
        description=(
            "VERBATIM excerpt from the narrative supporting this "
            "change. If you cannot find explicit text, do NOT emit."
        ),
    )


class InventoryChange(BaseModel):
    action: str = Field(..., description="'add' | 'remove'")
    item_id: str = Field(..., description="Canonical item id.")
    quantity: int = Field(default=1, ge=0, le=999)
    evidence: str = Field(..., description="Verbatim narrative excerpt.")


class CharacterStateChange(BaseModel):
    """Coarse-grained character state change. The backend
    applies these via jsonb_set on character_states.semantic_profile."""

    stamina_level: str | None = None
    health_status: str | None = None
    morale_level: str | None = None
    evidence: str = Field(..., description="Verbatim narrative excerpt.")


class StateMutation(BaseModel):
    """The complete structured output from the state extractor."""

    npc_status_changes: list[NPCStatusChange] = Field(default_factory=list)
    inventory_changes: list[InventoryChange] = Field(default_factory=list)
    character_state_changes: list[CharacterStateChange] = Field(default_factory=list)
    location_change: str | None = None


# ============================================
# LM Studio client (OpenAI-compatible)
# ============================================


class StateExtractor:
    """Calls LM Studio's OpenAI-compatible chat completions
    endpoint, running Gemma-4 12B with temperature=0."""

    def __init__(
        self,
        base_url: str | None = None,
        model: str | None = None,
        timeout: float = 30.0,
    ) -> None:
        self.base_url = (
            base_url
            or os.getenv("LLM_LOCAL_BASE_URL", "http://127.0.0.1:1234/v1")
        ).rstrip("/")
        self.model = model or os.getenv("LLM_LOCAL_MODEL", "gemma-3-12b-it")
        self.timeout = timeout
        self._client: httpx.AsyncClient | None = None

    async def _get_client(self) -> httpx.AsyncClient:
        if self._client is None:
            self._client = httpx.AsyncClient(timeout=self.timeout)
        return self._client

    async def aclose(self) -> None:
        if self._client is not None:
            await self._client.aclose()
            self._client = None

    async def health(self) -> bool:
        try:
            client = await self._get_client()
            r = await client.get(f"{self.base_url}/models")
            return r.status_code == 200
        except Exception:
            return False

    async def extract(
        self,
        narrative: str,
        player_choice: dict[str, Any],
        current_character_state: dict[str, Any],
        current_npc_states: list[dict[str, Any]],
    ) -> StateMutation:
        """Call Gemma-4 12B and parse the result as a StateMutation.

        Returns an empty StateMutation (no changes) on any
        failure. Never raises — extraction is best-effort.
        """
        # System prompt: STRICT extraction discipline
        # Gemma 4 12B-specific: T=0.0 + 嚴格 JSON 規範 + 顯式 output format marker
        system_prompt = (
            "你是 OpenClaw Sandbox RPG 嘅 state extractor（守門人）。\n"
            "Your task: extract EXPLICIT state changes from the narrative.\n"
            "OUTPUT FORMAT: JSON only, no prose, no markdown, no explanation.\n"
            "Your response MUST start with { and end with }.\n"
            "\n"
            "## 強制規則\n"
            "1. **只返回 JSON object**。Start with {, end with }.\n"
            "2. **只抽取 narrative 內 EXPLICITLY 提到嘅事實**。\n"
            "   - 唔做 inference\n"
            "   - 唔做 assumption\n"
            "   - 唔補完 narrative 冇講嘅嘢\n"
            "3. 每個改變都必須有 `evidence` field，引用 narrative 原文 verbatim。\n"
            "4. 如果 narrative 冇提到任何改變，返回空 mutations `{}`。\n"
            "5. NPC id 用小寫 snake_case (e.g. 'npc_halia_thornton')。\n"
            "6. evidence 必須係 narrative 內 verbatim 嘅一句或半句，唔可以 paraphrase。\n"
            "\n"
            "## JSON Schema (嚴格遵守)\n"
            '{"npc_status_changes": [...], "inventory_changes": [...], "character_state_changes": [...], "location_change": "..."}\n'
            "\n"
            "## Few-shot 範例 (照樣做)\n"
            "\n"
            "Input narrative: '你用鐵劍刺穿了 Harbin 的胸膛，他倒在地上不再動彈。'\n"
            "Output:\n"
            '{"npc_status_changes": [{"npc_id": "npc_harbin_west", "new_status": "dead", "evidence": "你用鐵劍刺穿了 Harbin 的胸膛，他倒在地上不再動彈"}], "inventory_changes": [], "character_state_changes": [], "location_change": null}\n'
            "\n"
            "Input narrative: 'Sister Garaele 微笑著遞給你一個小袋子，裡面裝著三枚銀幣。'\n"
            "Output:\n"
            '{"npc_status_changes": [], "inventory_changes": [{"action": "add", "item_id": "small_pouch", "quantity": 1, "evidence": "Sister Garaele 微笑著遞給你一個小袋子"}, {"action": "add", "item_id": "silver_coin", "quantity": 3, "evidence": "裡面裝著三枚銀幣"}], "character_state_changes": [], "location_change": null}\n'
            "\n"
            "Input narrative: '你站在 Phandalin 鎮中心，四周的木屋包圍著你。'\n"
            "Output:\n"
            '{"npc_status_changes": [], "inventory_changes": [], "character_state_changes": [], "location_change": null}\n'
            "  (narrative 只描述場景，冇 state 改變，return empty)\n"
            "\n"
            "## Final reminder\n"
            "Return JSON only. No preamble. No explanation. No code fences.\n"
            "First character MUST be {. Last character MUST be }."
        )

        # User message: per-round context
        current_npc_summary = json.dumps(
            current_npc_states, ensure_ascii=False, default=str
        )
        choice_summary = json.dumps(
            player_choice, ensure_ascii=False, default=str
        )
        char_summary = json.dumps(
            current_character_state, ensure_ascii=False, default=str
        )
        user_message = (
            f"## 當前角色狀態\n{char_summary}\n\n"
            f"## 當前場景 NPC 狀態\n{current_npc_summary}\n\n"
            f"## 玩家嘅選擇\n{choice_summary}\n\n"
            f"## Narrative (本輪)\n{narrative}\n\n"
            "## 輸出 (JSON only, no prose, no markdown):"
        )

        try:
            client = await self._get_client()
            r = await client.post(
                f"{self.base_url}/chat/completions",
                json={
                    "model": self.model,
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_message},
                    ],
                    "temperature": 0,  # greedy, deterministic
                    "top_p": 1,
                    "top_k": 1,  # Gemma supports top_k=1 for hard greedy
                    "max_tokens": 500,
                    "stop": ["```", "<end_of_turn>"],
                    "seed": 42,
                },
            )
            data = r.json()
            msg = data["choices"][0]["message"]
            # Gemma 4 12B QAT (and other reasoning-capable models)
            # may emit JSON in 'reasoning_content' field with empty
            # 'content' field. Read both, prefer the non-empty one.
            text = (msg.get("content") or "").strip()
            if not text:
                text = (msg.get("reasoning_content") or "").strip()
            if not text:
                logger.warning("[StateExtractor] Both content and reasoning_content empty")
                return StateMutation()
        except Exception as e:
            logger.warning(f"[StateExtractor] LLM call failed: {e}")
            return StateMutation()

        # Parse the JSON. Try strict parse, then fall back to
        # brace-balanced extraction (LM Studio can occasionally
        # prepend a stray space or newline).
        parsed: dict[str, Any] | None = None
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            # Find first '{' and matching '}'
            start = text.find("{")
            if start >= 0:
                depth = 0
                in_string = False
                escape = False
                for end in range(start, len(text)):
                    ch = text[end]
                    if escape:
                        escape = False
                        continue
                    if ch == "\\":
                        escape = True
                        continue
                    if ch == '"':
                        in_string = not in_string
                        continue
                    if in_string:
                        continue
                    if ch == "{":
                        depth += 1
                    elif ch == "}":
                        depth -= 1
                        if depth == 0:
                            try:
                                parsed = json.loads(text[start : end + 1])
                            except json.JSONDecodeError:
                                pass
                            break

        if parsed is None:
            logger.warning(
                f"[StateExtractor] Could not parse JSON from LLM: {text[:200]}"
            )
            return StateMutation()

        # Validate via Pydantic
        try:
            return StateMutation.model_validate(parsed)
        except ValidationError as e:
            logger.warning(
                f"[StateExtractor] Pydantic validation failed: {e}"
            )
            # Best-effort: try to salvage NPC status changes only
            try:
                salvaged = {"npc_status_changes": parsed.get("npc_status_changes", [])}
                return StateMutation.model_validate(salvaged)
            except ValidationError:
                return StateMutation()


# ============================================
# Singleton accessor
# ============================================

_extractor: StateExtractor | None = None


def get_state_extractor() -> StateExtractor:
    """Return the singleton StateExtractor instance."""
    global _extractor
    if _extractor is None:
        _extractor = StateExtractor()
    return _extractor
