"""
State Extractor (Phase L2-I/Phase C-6)
=====================================

A background "gatekeeper" LLM that watches the narrative
generated by MiniMax-M3 and extracts structured state
mutations. Runs on the **local** LM Studio instance
(BAZOOKA), serving Gemma-4 12B (or Gemma-3 12B-Instruct).
Uses temperature=0 (greedy) for full determinism.

Architecture:
  ┌──────────────────────┐
  │  Cloud MiniMax-M3     │  (authoritative narrator)
  └──────────┬───────────┘
             │ narrative + choices
             ↓
  ┌──────────────────────┐    ┌──────────────────────┐
  │  Backend Q6 STEP 2   │ →  │  State Extractor     │
  │  (game_socket.py)    │    │  (this module)       │
  └──────────────────────┘    │  LM Studio:1234      │
                              │  Gemma-4 12B         │
                              │  temperature=0        │
                              └──────────┬───────────┘
                                         │ StateMutation
                                         ↓
                              scene_npc_states, character_states

Key design choices (Phase L2-I/Phase C-6):

  1. STRICT EXTRACTION ONLY — never infers, never
     invents. If the narrative doesn't explicitly state a
     fact, returns empty mutations. The few-shot examples
     and the system prompt enforce this discipline.

  2. EVIDENCE BINDING — every state change must cite a
     verbatim excerpt from the narrative. Cross-validation
     can later check that the cited text actually exists.

  3. DELTA-ONLY OUTPUT — the extractor returns the *change*
     (e.g. {"npc_id": "harbin", "new_status": "dead"}), not
     the absolute state. The backend applies the delta to
     the existing row idempotently.

  4. GREEDY DECODING (T=0) — full determinism so two
     extracts of the same narrative produce byte-identical
     JSON. This is critical for replay safety and idempotency.

  5. ASYNC PARALLEL — runs in parallel with the M3 narrative
     call (asyncio.gather). Does not block the user-facing
     response.

  6. PYDANTIC SCHEMA — strict typing at the API boundary
     catches any malformed JSON before it touches the DB.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
from typing import Any

import httpx
from pydantic import BaseModel, Field, ValidationError

logger = logging.getLogger(__name__)


# ============================================
# Pydantic schema (strict typing for DB write)
# ============================================


class NPCStatusChange(BaseModel):
    """A single NPC's status change detected from the narrative."""

    npc_id: str = Field(
        ...,
        description="The canonical NPC id (e.g. 'npc_halia_thornton').",
    )
    new_status: str = Field(
        ...,
        description=(
            "One of: 'alive' | 'dead' | 'fled' | 'unconscious' | "
            "'hostile' | 'neutral' | 'friendly' | 'absent'."
        ),
    )
    evidence: str = Field(
        ...,
        description=(
            "VERBATIM excerpt from the narrative supporting this "
            "change. If you cannot find explicit text, do NOT emit."
        ),
    )


class InventoryChange(BaseModel):
    action: str = Field(..., description="'add' | 'remove'")
    item_id: str = Field(..., description="Canonical item id.")
    quantity: int = Field(default=1, ge=0, le=999)
    evidence: str = Field(..., description="Verbatim narrative excerpt.")


class CharacterStateChange(BaseModel):
    """Coarse-grained character state change. The backend
    applies these via jsonb_set on character_states.semantic_profile."""

    stamina: str | None = None
    health: str | None = None
    morale: str | None = None
    stamina_level: str | None = None
    health_status: str | None = None
    morale_level: str | None = None
    evidence: str = Field(..., description="Verbatim narrative excerpt.")


class StateMutation(BaseModel):
    """The complete structured output from the state extractor."""

    npc_status_changes: list[NPCStatusChange] = Field(default_factory=list)
    inventory_changes: list[InventoryChange] = Field(default_factory=list)
    character_state_changes: list[CharacterStateChange] = Field(default_factory=list)
    location_change: str | None = None


# ============================================
# LM Studio client (OpenAI-compatible)
# ============================================


class StateExtractor:
    """Calls LM Studio's OpenAI-compatible chat completions
    endpoint, running Gemma-4 12B with temperature=0."""

    def __init__(
        self,
        base_url: str | None = None,
        model: str | None = None,
        timeout: float = 30.0,
    ) -> None:
        self.base_url = (
            base_url
            or os.getenv("LLM_LOCAL_BASE_URL", "http://127.0.0.1:1234/v1")
        ).rstrip("/")
        self.model = model or os.getenv("LLM_LOCAL_MODEL", "gemma-3-12b-it")
        self.timeout = timeout
        self._client: httpx.AsyncClient | None = None

    async def _get_client(self) -> httpx.AsyncClient:
        if self._client is None:
            self._client = httpx.AsyncClient(timeout=self.timeout)
        return self._client

    async def aclose(self) -> None:
        if self._client is not None:
            await self._client.aclose()
            self._client = None

    async def health(self) -> bool:
        try:
            client = await self._get_client()
            r = await client.get(f"{self.base_url}/models")
            return r.status_code == 200
        except Exception:
            return False

    async def extract(
        self,
        narrative: str,
        player_choice: dict[str, Any],
        current_character_state: dict[str, Any],
        current_npc_states: list[dict[str, Any]],
    ) -> StateMutation:
        """Call Gemma-4 12B and parse the result as a StateMutation.

        Returns an empty StateMutation (no changes) on any
        failure. Never raises — extraction is best-effort.
        """
        # System prompt: STRICT extraction discipline
        # Separates rules, definitions, and output format strictly.
        # Allows Markdown code block output.
        system_prompt = (
            "你是 OpenClaw Sandbox RPG 的 State Extractor（守門人）。\n"
            "你的唯一任務是分析「遊戲敘事 (Narrative)」，並嚴格根據「當前狀態 (Current State)」推斷出發生了什麼物理或數值改變。\n"
            "\n"
            "## 鐵律 (Hard Rules)\n"
            "1. 必須基於敘事中「已經發生且明確」的物理改變。不作任何主觀猜測、不計算潛在意圖。\n"
            "2. 角色「感覺」、「似乎」、「打算」不構成狀態改變。\n"
            "3. 如果沒有發生任何實質改變，必須回傳空的 JSON 物件，即所有的 changes 為空列表且 location_change 為 null：\n"
            "   {\"npc_status_changes\": [], \"inventory_changes\": [], \"character_state_changes\": [], \"location_change\": null}\n"
            "4. 任何改變必須附帶 `evidence`，且必須 100% verbatim (一字不漏) 引用敘事中的原文。\n"
            "5. NPC id 用小寫 snake_case (例如 'npc_halia_thornton')。\n"
            "6. location_change 必須是具體的 scene_id (例如 'loc_phandalin_tresendar')，絕對不能填寫敘事中的中文文字！如果敘事中沒有明確指出場景 ID，請填寫 null。\n"
            "\n"
            "## 輸出格式 (Output Format)\n"
            "你必須將結果以 JSON 格式輸出，並使用 ```json 和 ``` 包裹。不要在代碼塊外寫任何廢話。你的 Reasoning 思考過程可以放在 Markdown 代碼塊之外或以模型自帶的思考欄位輸出，但最終結果必須有且僅有一個 ```json 代碼塊包裹。\n"
            "\n"
            "## JSON Schema 結構要求\n"
            "{\n"
            "  \"npc_status_changes\": [\n"
            "    {\n"
            "      \"npc_id\": \"string (NPC 的 canonical ID)\",\n"
            "      \"new_status\": \"string ('alive' | 'dead' | 'fled' | 'unconscious' | 'hostile' | 'neutral' | 'friendly' | 'absent')\",\n"
            "      \"evidence\": \"string (一字不漏引用的敘事原文)\"\n"
            "    }\n"
            "  ],\n"
            "  \"inventory_changes\": [\n"
            "    {\n"
            "      \"action\": \"string ('add' | 'remove')\",\n"
            "      \"item_id\": \"string (Canonical item id)\",\n"
            "      \"quantity\": \"integer (預設為 1)\",\n"
            "      \"evidence\": \"string (一字不漏引用的敘事原文)\"\n"
            "    }\n"
            "  ],\n"
            "  \"character_state_changes\": [\n"
            "    {\n"
            "      \"stamina\": \"string | null (例如 'fresh' | 'exhausted')\",\n"
            "      \"health\": \"string | null (例如 'healthy' | 'wounded' | 'critical')\",\n"
            "      \"morale\": \"string | null (例如 'calm' | 'panicked')\",\n"
            "      \"evidence\": \"string (一字不漏引用的敘事原文)\"\n"
            "    }\n"
            "  ],\n"
            "  \"location_change\": \"string | null (Canonical scene_id)\"\n"
            "}\n"
            "\n"
            "## Few-shot 範例\n"
            "\n"
            "Input narrative: '你用鐵劍刺穿了 Harbin 的胸膛，他倒在地上不再動彈。'\n"
            "Output:\n"
            "```json\n"
            "{\n"
            "  \"npc_status_changes\": [\n"
            "    {\n"
            "      \"npc_id\": \"npc_harbin_west\",\n"
            "      \"new_status\": \"dead\",\n"
            "      \"evidence\": \"你用鐵劍刺穿了 Harbin 的胸膛，他倒在地上不再動彈\"\n"
            "    }\n"
            "  ],\n"
            "  \"inventory_changes\": [],\n"
            "  \"character_state_changes\": [],\n"
            "  \"location_change\": null\n"
            "}\n"
            "```\n"
            "\n"
            "Input narrative: 'Sister Garaele 微笑著遞給你一個小袋子，裡面裝著三枚銀幣。'\n"
            "Output:\n"
            "```json\n"
            "{\n"
            "  \"npc_status_changes\": [],\n"
            "  \"inventory_changes\": [\n"
            "    {\n"
            "      \"action\": \"add\",\n"
            "      \"item_id\": \"small_pouch\",\n"
            "      \"quantity\": 1,\n"
            "      \"evidence\": \"Sister Garaele 微笑著遞給你一個小袋子\"\n"
            "    },\n"
            "    {\n"
            "      \"action\": \"add\",\n"
            "      \"item_id\": \"silver_coin\",\n"
            "      \"quantity\": 3,\n"
            "      \"evidence\": \"裡面裝著三枚銀幣\"\n"
            "    }\n"
            "  ],\n"
            "  \"character_state_changes\": [],\n"
            "  \"location_change\": null\n"
            "}\n"
            "```\n"
            "\n"
            "Input narrative: '你站在 Phandalin 鎮中心，四周的木屋包圍著你。'\n"
            "Output:\n"
            "```json\n"
            "{\n"
            "  \"npc_status_changes\": [],\n"
            "  \"inventory_changes\": [],\n"
            "  \"character_state_changes\": [],\n"
            "  \"location_change\": null\n"
            "}\n"
            "```\n"
            "\n"
            "Input narrative: 'Harbin 似乎對你抱有敵意，但他還沒有明顯動手。'\n"
            "Output:\n"
            "```json\n"
            "{\n"
            "  \"npc_status_changes\": [],\n"
            "  \"inventory_changes\": [],\n"
            "  \"character_state_changes\": [],\n"
            "  \"location_change\": null\n"
            "}\n"
            "```\n"
            "\n"
            "Input narrative: '你離開了 Phandalin 鎮，踏入 Tresendar Manor 的廢墟。'\n"
            "Output:\n"
            "```json\n"
            "{\n"
            "  \"npc_status_changes\": [],\n"
            "  \"inventory_changes\": [],\n"
            "  \"character_state_changes\": [],\n"
            "  \"location_change\": \"loc_phandalin_tresendar\"\n"
            "}\n"
            "```\n"
        )

        # User message: per-round context
        current_npc_summary = json.dumps(
            current_npc_states, ensure_ascii=False, default=str
        )
        choice_summary = json.dumps(
            player_choice, ensure_ascii=False, default=str
        )
        char_summary = json.dumps(
            current_character_state, ensure_ascii=False, default=str
        )
        user_message = (
            f"### [Current State]\n"
            f"當前角色狀態: {char_summary}\n"
            f"當前 NPC 狀態: {current_npc_summary}\n"
            f"玩家嘅選擇: {choice_summary}\n\n"
            f"### [Narrative to Analyze]\n"
            f"{narrative}\n\n"
            f"### 提取結果:"
        )

        try:
            client = await self._get_client()
            r = await client.post(
                f"{self.base_url}/chat/completions",
                json={
                    "model": self.model,
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_message},
                    ],
                    "temperature": 0,  # greedy, deterministic
                    "top_p": 1,
                    "top_k": 1,  # Gemma supports top_k=1 for hard greedy
                    "max_tokens": 1200,  # 增加到 1200 因中文字符 count 高
                    "stop": ["<end_of_turn>"],  # Remove "```" from stop tokens to allow markdown code fence output
                    "seed": 42,
                },
            )
            data = r.json()
            msg = data["choices"][0]["message"]
            # Gemma 4 12B QAT (and other reasoning-capable models)
            # may emit JSON in 'reasoning_content' field with empty
            # 'content' field. Read both, prefer the non-empty one.
            text = (msg.get("content") or "").strip()
            if not text:
                text = (msg.get("reasoning_content") or "").strip()
            print(f"\n[DEBUG StateExtractor Raw Text]:\n{text}\n")
            if not text:
                logger.warning("[StateExtractor] Both content and reasoning_content empty")
                return StateMutation()
        except Exception as e:
            logger.warning(f"[StateExtractor] LLM call failed: {e}")
            return StateMutation()

        # Defensively parse the JSON.
        import re
        parsed: dict[str, Any] | None = None
        
        # Split CoT (Reasoning) process to avoid interference from JSON snippets inside <think>
        main_content = text
        if "</think>" in text:
            main_content = text.split("</think>")[-1].strip()
        
        # 1. Search for ```json ... ``` code fence block (allowing unclosed fences)
        json_match = re.search(r"```json\s*(.*?)\s*(?:```|$)", main_content, re.DOTALL)
        if json_match:
            try:
                parsed = json.loads(json_match.group(1).strip())
            except json.JSONDecodeError:
                pass
        
        # 2. Fallback: Search for the first { and the last } in the cleaned main_content
        if parsed is None:
            fallback_match = re.search(r"(\{.*\})", main_content, re.DOTALL)
            if fallback_match:
                try:
                    parsed = json.loads(fallback_match.group(1).strip())
                except json.JSONDecodeError:
                    pass

        # 3. Fallback: Brace-balanced extraction (original logic for deep defense)
        if parsed is None:
            start = main_content.find("{")
            if start >= 0:
                depth = 0
                in_string = False
                escape = False
                for end in range(start, len(main_content)):
                    ch = main_content[end]
                    if escape:
                        escape = False
                        continue
                    if ch == "\\":
                        escape = True
                        continue
                    if ch == '"':
                        in_string = not in_string
                        continue
                    if in_string:
                        continue
                    if ch == "{":
                        depth += 1
                    elif ch == "}":
                        depth -= 1
                        if depth == 0:
                            try:
                                parsed = json.loads(main_content[start : end + 1])
                            except json.JSONDecodeError:
                                pass
                            break

        if parsed is None:
            logger.warning(
                f"[StateExtractor] Could not parse JSON from LLM: {text[:200]}"
            )
            return StateMutation()

        # Validate via Pydantic
        try:
            return StateMutation.model_validate(parsed)
        except ValidationError as e:
            logger.warning(
                f"[StateExtractor] Pydantic validation failed: {e}"
            )
            # Best-effort: try to salvage NPC status changes only
            try:
                salvaged = {"npc_status_changes": parsed.get("npc_status_changes", [])}
                return StateMutation.model_validate(salvaged)
            except ValidationError:
                return StateMutation()


# ============================================
# Singleton accessor
# ============================================

_extractor: StateExtractor | None = None


def get_state_extractor() -> StateExtractor:
    """Return the singleton StateExtractor instance."""
    global _extractor
    if _extractor is None:
        _extractor = StateExtractor()
    return _extractor
