"""initial characters scenes worlds

Revision ID: 401b2472fd72
Revises: 
Create Date: 2026-06-04 17:04:39.481416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '401b2472fd72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('character_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('world_id', sa.String(length=128), nullable=False),
    sa.Column('json_state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('character_id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_world_id'), ['world_id'], unique=False)

    op.create_table('worlds',
    sa.Column('world_id', sa.String(length=128), nullable=False),
    sa.Column('json_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('world_id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.String(length=128), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('json_output', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_character_id'), ['character_id'], unique=False)
        batch_op.create_index('ix_scenes_character_round', ['character_id', 'round'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenes_round'), ['round'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_round'))
        batch_op.drop_index('ix_scenes_character_round')
        batch_op.drop_index(batch_op.f('ix_scenes_character_id'))

    op.drop_table('scenes')
    op.drop_table('worlds')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_world_id'))

    op.drop_table('characters')
    # ### end Alembic commands ###
